# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: James Eagle
title: Tech Lead and Software Engineer
email: james@jeagle.co
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  regaleagle
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: james-eagle
linkedin_username: james-eagle
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A software developer at heart, really I just love solving problems: algorithmic, organisational, architectural, in-code or in the real world - especially those that require a trip to the hardware store. Solutions absolutely not guaranteed for that last sub-category. As an Australian in Sweden I have severe beach withdrawals but I am slowly acclimatising to the ice water.

  I have 7 years experience as a professional full stack web developer, the last 2 of which have been as the Tech Lead for a team of 18. I try to lead by example and work hard to maintain my own technical competence and contributions. My primary mission though is empowering my team to achieve their own goals through process and structural improvement, as well as being involved in mentoring and education.

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Visit Group
        link: visit.com
        # link_text: boringcompany.com
        sub_title: Tech Lead
        caption: June 2021 - Present
        quote: >
          Technical lead and exploratory engineer for Citybreak
        description: | # this will include new lines to allow paragraphs
          Citybreak is the Central Reservation System for Visit Group, both a product and a business unit. Visit provides an e-commerce SaaS product suite and platform for tourism. 
          As tech lead, I am responsible for setting the technical roadmap of the Citybreak part of the platform. 
          The primary goals are to improve the reliability, performance and maintainability of our battle-tested (mostly) .Net codebase - as well as helping guide product development. 
          I lead 3 teams so I am also responsible for improving processes, guidance and mentoring of 18 developers. 
          I continue to actively contribute code for POCs, sensitive projects, troubleshooting and while pairing with our junior team members
          Tech:
          <mark>.NET Framework</mark> <mark>.NET Core</mark> <mark>C#</mark> <mark>JavaScript</mark> <mark>Vue.js</mark> <mark>TypeScript</mark> <mark>RabbitMQ</mark> <mark>Open Telemetry</mark> <mark>Redis</mark> <mark>MongoDB</mark> <mark>Elasticsearch</mark> <mark>Azure DevOps</mark> <mark>Octopus Deploy</mark> <mark>SQL Server</mark> <mark>VMWare</mark> 
      - layout: left
        title: Visit Group
        link: visit.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: October 2016 - 2021
        quote: >
          Junior -> Senior at Visit
        description: | # this will include new lines to allow paragraphs
          After a career change, I started in the Citybreak business unit at Visit as a junior in 2016. 
          For the next few years I worked across our whole tech stack: .Net Framework & Core backend services, various combos of Asp.Net, Vue.Js and JQuery solutions for widgets, white-label front-end solutions and back office tools. 
          Maintained SQL Server, Redis, Mongo, Elastic Search installations among others.
          After a few years I became a de-facto lead of our core team. Along the way I pioneered a number of new services and tools, in particular those targeting external integrations
          Managing basic dev-ops for the on-prem setup was also an important part of the role
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Gothenburg University
        caption: 2013 - 2016
        sub_title: BSc Software Engineering and Management
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          A collaboration between GU and Chalmers University. 
          It has a practical, group-project based curriculum focused on designing and implementing software systems in a systematic fashion with quantifiable outcomes.
          Tech:
          <mark>Erlang</mark> <mark>C++</mark> <mark>Haskell</mark> <mark>Java</mark>

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: References on requests

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]